const String kEtiquettesPara1 =
    'Getting close to a Deaf person requires a little vulnerability on both sides. Many Deaf people are just as insecure about not being understood as you are, but most are patient and incredibly skilled at getting their point across to you.';
const String kEtiquettesPara2 =
    'Think about how would you feel if you were living in a foreign land where the language, customs, and culture weren’t native to you? Deaf people often feel this way when surrounded by hearing people';
const String kEtiquettesPara3 =
    '"Deaf and dumb” is an insulting way to label a Deaf person. You should instead just say Deaf, a scientifically proven and respectful way. When writing or exchanging correspondence, the word Deaf should always start with capital “D”, as if you are addressing the “Mr.” and “Mrs.” titles.';
const String kDosPara =
    '1. During introductions, always introduce yourself first and use the sign language alphabet to fingerspell your name. The Deaf Community gives name signs to people. Those who can hear don’t invent their own, nor do they give name signs to each other.\n\n2. When fingerspelling or signing, keep a steady hand. Your signs are easier to read when your hand is not shaking.\n\n3. Maintain eye contact and make your approach (non-signers may view this action as staring and think that it is rude, but in the world of sign, making and maintaining eye contact is a necessary common practice).';
const String kDontsPara =
    '1. Don’t grab or poke when you walk up behind a Deaf person. This action is commonly used as a warning that something is wrong or in an emergency.\n\n2. Never throw objects at a Deaf person to get his or her attention. Besides being just plain rude, it is also dangerous.\n\n3. Chewing gum is a no-no in sign language. Mouth movement is an important part of signed communications.\n\n4. When you see two people are signing secretly, don’t stare. They might be having a private conversation.\n\n5. When visiting Deaf people, don’t just walk into the house since they can’t hear the doorbell. Deaf people have strobe lights connected to the doorbell and the phone. When either ring, a light will flash.\n\n6. If you are out for a meal with a Deaf person, don’t order for them unless you are asked. They are accustomed to pointing at an item on the menu to the server.\n\n7. Never initiate a conversation about a Deaf person’s hearing loss. Questioning implies that you don’t view that person as a whole, but broken, incomplete, or inferior. It is a sensitive subject.\n\n8. Don’t stand where bright light or sun is directly behind you because whoever is watching you sign will only see your silhouette – a big giveaway that you are a beginner.';
const String kCommunicationTips =
    '1. Use a normal speaking pattern.\n\nOver-enunciating makes it hard for a Deaf person to read your lips.\n\n2. Write it down if necessary.\n\nSome people are better at reading lips than others.\n\n3. Look directly at the person you are communicating with.\n\nIf you look away, a Deaf person may miss what you are saying.\n\n4. Speak in a normal tone of voice.\n\nSince a Deaf person cannot hear you, raising your voice doesn’t help.\n\n5. Try to find your own way to communicate.\n\nAlthough you can’t talk to one another, there are many other ways for you to communicate. You can use a pen and paper or even text to have a conversation.\n\n6. Don’t be afraid to ask a Deaf person to repeat themselves.\n\nThe goal is clear communication and understanding. Asking to repeat something has better results and less frustration – for both parties.\n\n7. Be patient and inclusive.\n\nImagine you are trying to understand a conversation that you want to be involved in, but are unable due to the conversation’s speed, number of people talking at the same time, and/or not being able to share your ideas with the group. By allowing enough time and considering the communication needs of everyone in the group, you ensure that everyone can participate fully.\n\n8. In a group conversation, take turns speaking.\n\nA Deaf person can only look at one individual at a time.\n\n9. Be clear and concise.\n\nSaying “I’m fine” can have many different meanings with subtle differences. For example “I’m fine” can mean:\n◦I feel well\n◦I feel the same way I always feel\n◦I’m way too busy to know how I feel\n◦Don’t bother me\n◦Did you want to know about my emotional or physical well-being?\n◦You don’t care how I feel or would have stopped walking to listen.\n\n10. Use body language and gestures.\n\nDeaf and hard of hearing people who use sign language are accustomed to using their hands and face to communicate. Gesturing and using clear facial expressions when speaking to a person with hearing challenges can help them understand what you’re saying. “Miming” is also acceptable if it helps to get a certain point across, but remember that mime is not the same as sign language.\n\n 11. Accept that awkward moments happen.\n\nEven if you follow all of the above tips while speaking to a Deaf or hard of hearing person, they’ll probably still misunderstand you at some point. Don’t feel bad or stop. Just repeat yourself and continue the conversation. If they’re having trouble understanding a certain word or phrase, try using a different word, rephrasing what you said, or typing it on your phone.\n\n12. Resist the urge to give up when misunderstandings happen.\n\nA little effort on your part can make a big difference to someone, and chances are that you’ll benefit from the experience, too.';
