const String kEtiquettesPara1 =
    'Getting close to a Deaf person requires a little vulnerability on both sides. Many Deaf people are just as insecure about not being understood as you are, but most are patient and incredibly skilled at getting their point across to you.';
const String kEtiquettesPara2 =
    'Think about how would you feel if you were living in a foreign land where the language, customs, and culture weren’t native to you? Deaf people often feel this way when surrounded by hearing people';
const String kEtiquettesPara3 =
    '"Deaf and dumb” is an insulting way to label a Deaf person. You should instead just say Deaf, a scientifically proven and respectful way. When writing or exchanging correspondence, the word Deaf should always start with capital “D”, as if you are addressing the “Mr.” and “Mrs.” titles.';
const String kDosPara =
    '1. During introductions, always introduce yourself first and use the sign language alphabet to fingerspell your name. The Deaf Community gives name signs to people. Those who can hear don’t invent their own, nor do they give name signs to each other.\n\n2. When fingerspelling or signing, keep a steady hand. Your signs are easier to read when your hand is not shaking.\n\n3. Maintain eye contact and make your approach (non-signers may view this action as staring and think that it is rude, but in the world of sign, making and maintaining eye contact is a necessary common practice).';
const String kDontsPara =
    '1. Don’t grab or poke when you walk up behind a Deaf person. This action is commonly used as a warning that something is wrong or in an emergency.\n\n2. Never throw objects at a Deaf person to get his or her attention. Besides being just plain rude, it is also dangerous.\n\n3. Chewing gum is a no-no in sign language. Mouth movement is an important part of signed communications.\n\n4. When you see two people are signing secretly, don’t stare. They might be having a private conversation.\n\n5. When visiting Deaf people, don’t just walk into the house since they can’t hear the doorbell. Deaf people have strobe lights connected to the doorbell and the phone. When either ring, a light will flash.\n\n6. If you are out for a meal with a Deaf person, don’t order for them unless you are asked. They are accustomed to pointing at an item on the menu to the server.\n\n7. Never initiate a conversation about a Deaf person’s hearing loss. Questioning implies that you don’t view that person as a whole, but broken, incomplete, or inferior. It is a sensitive subject.\n\n8. Don’t stand where bright light or sun is directly behind you because whoever is watching you sign will only see your silhouette – a big giveaway that you are a beginner.';
